# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7003
  connection-timeout: 5000ms
  servlet:
    context-path: /shard-jdbc

spring:
  application:
    name: ware-shard-jdbc
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 192.168.1.114
    port: 6379
    password:
# mybatis
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml